config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    get 'oka', to: 'devise/sessions#new'
  end
  resources :works do
    delete :destroy_img, on: :member
  end
  resources :categories, path: "" do
    delete :destroy_img, on: :member
  end
  root "categories#index"

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  include Image
  include Slugable
  has_ancestry
  has_one_attached :image
  has_many :works, dependent: :destroy
  validates :name, :image, presence: true
end

app/models/concerns/image.rb
module Image
  def thumbnail
    return image.variant(resize: '300x').processed if image.attached?
  end

  def standart_images
    return images.map { |image| image.variant(resize: '1000x').processed.processed } if images.attached?
  end
end

app/models/concerns/slugable.rb
module Slugable
  extend ActiveSupport::Concern

  included do
    before_save :set_slug
    validates   :slug, uniqueness: true
  end

  def to_param
    return unless persisted?

    slug
  end

  private

  def set_slug
    self.slug = name.to_s.parameterize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  include Image
  include Slugable
  has_one_attached :image
  has_many_attached :images
  belongs_to :category
  validates :name, :image, :images, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:show, :index]
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy, :destroy_img]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.roots.order(created_at: :desc)
  end

  def destroy_img
    @category.image.purge
    redirect_back(fallback_location: root_path)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.create!(category_params)
    # session[:user_id] = user.id
    thumbnail = params[:category][:thumbnail]
    @user.thumbnail.attach(thumbnail) if thumbnail
    redirect_to root_path
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find_by(slug: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :image, :parent_id, :slug)
    end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy, :destroy_img]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all.order(created_at: :desc)
  end

  def destroy_img
    @work.images.purge
    redirect_back(fallback_location: root_path)
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find_by(slug: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def work_params
      params.require(:work).permit(:name, :category_id, :slug, :image, images: [])
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/categories/_children_category.html.haml
.categories-container
  - categories.each do |child|
    = link_to child do
      .category-container
        - if child.image.attached?
          = image_tag(child.thumbnail)
        %h4= child.name

app/views/categories/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@category) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :parent_id, collection: Category.all, include: :blank
    = f.input :name
    - if @category.image.attached?
      = image_tag @category.thumbnail
      -# = link_to 'Delete image', destroy_img_category_path(@category), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger"
    = f.file_field :image

  .form-actions
    = f.button :submit, class: "btn-success"

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'
%ul
  %li= link_to 'Show', @category, class: "btn btn-primary"
  %li= link_to 'Delete category', @category, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"

app/views/categories/index.html.haml
= render partial: 'children_category', locals: { categories: @categories }

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
= render partial: 'shared/header', locals: { object_name: @category }

- if @category.children?
  = render partial: 'children_category', locals: { categories: @category.children }

- if @category.works.present? && !@category.children?
  .categories-container
    - @category.works.each do |work|
      = link_to work do
        .category-container
          - if work.image.attached?
            = image_tag(work.thumbnail)
          = work.name

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Okaokoshko
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .logo
      %h1 OkaOkoshko
    .container
      = render partial: 'shared/root_menu'
      = yield
-# = console if Rails.env.development?

app/views/shared/_header.html.haml
.header
  .links
    %h1= link_to 'Home', root_path
    - if object_name.parent.present?
      .span
        \/
      %h2= link_to object_name.parent.name, object_name.parent
  - unless controller_name == 'works'
    %h3= object_name.name
    = link_to 'Edit', edit_category_path(object_name) if user_signed_in?

app/views/shared/_root_menu.html.haml
.header
  - if user_signed_in?
    %ul
      %li= link_to 'Home', root_path
      %li= link_to 'Add category', new_category_path
      %li= link_to 'Add work', new_work_path
      %li= link_to 'Sign out', destroy_user_session_path, method: :delete
  - else
    -# %ul
    -#   %li= link_to 'Home', root_path
    -#   %li= link_to 'Sign in', new_user_session_path

app/views/works/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@work) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :category
    = f.input :name
    .cover-image
      - if @work.image.attached?
        = image_tag @work.thumbnail
      %h2= f.label 'Cover image'
      = f.file_field :image
    .work-images
      .image
        - if @work.images
          - @work.images.each do |image|
            = image_tag image.variant(resize: '100x').processed.processed

      %h2= f.label 'Work images'
      = f.file_field :images, multiple: true, direct_upload: true

  .form-actions
    = f.button :submit, class: 'btn btn-success'

app/views/works/edit.html.haml
%h1 Editing work

= render 'form'

= link_to 'Show', @work
\|
= link_to 'Back', works_path

app/views/works/new.html.haml
%h1 New work

= render 'form'

= link_to 'Back', works_path

app/views/works/show.html.haml
%p#notice= notice


= render partial: 'shared/header', locals: { object_name: @work.category }

.work-container
  - if user_signed_in?
    = link_to 'Edit this work', edit_work_path(@work)
  %h3= @work.name
  - if @work.images.attached?
    - @work.images.each do |image|
      = image_tag(image)